### ISSUE TITLE
show only text "Hello world!", don't have any style?

### ISSUE THREAD

**Issue by yuomtheara** [lookback/meteor-dropdowns#1]
I tried, but don't show any style like background, border ... for popup (show only text "Hello world!").

**Comment by yuomtheara** [comment]
I think that it don't have `.css` build in.

**Comment by johanbrook** [comment]
That's correct, you need to style the dropdown yourself. See example SCSS in the https://github.com/lookback/meteor-dropdowns/blob/master/test-app/_dropdowns.scss file.

**Comment by yuomtheara** [comment]
Oh I don't understand `.scss`,
Now I base on `bootstrap 3` on my app, so could you example the `css` for this?

**Comment by johanbrook** [comment]
Sadly, I don't want to, nor have the time to create the custom CSS needed for people's dropdowns. I hope you understand. If you have decent CSS knowledge, it should be possible to take the basics out of the file I linked and convert it to CSS by hand.
