### ISSUE TITLE
Persistency

### ISSUE THREAD

**Issue by dominicarrojado** [lookback/meteor-dropdowns#10]
Why is the persistent argument is not working? 
{{#dropdown name="dropdown-name" persistent="true"}}
{{/dropdown}}

also tried without quotation marks 
{{#dropdown name="dropdown-name" persistent=true}}
{{/dropdown}}

still not working..
also, how could I implement nested dropdowns? How do I prevent the parent dropdown from closing?

**Comment by johanbrook** [comment]
Hm, this works in the demo at [dropdowns.meteor.com](http://dropdowns.meteor.com)? I added some docs on it: https://github.com/lookback/meteor-dropdowns#persistent-dropdowns

**Comment by dominicarrojado** [comment]
Hmm weird.. I also get error sometimes on when creating a new dropdown. It says that it cannot find the dropdown-name but I put the same name on the Trigger and the dropdown. Weird... And I change names until it works. Lol. Is it because of the theme I'm using has a bootstrap dropdown which somehow conflicts with each other?

**Comment by dominicarrojado** [comment]
![screen shot 2015-10-20 at 10 43 15 am](https://cloud.githubusercontent.com/assets/13690375/10596507/8081cf5e-7717-11e5-95c6-3f62efc3ee4d.png)

This is what I'm talking about, I just followed the doc.

**Comment by dominicarrojado** [comment]
I noticed that it works on other template but some template it couldn't find a dropdown. Also when I'm able to create a dropdown the persistency still doesn't work.. Is it because of the bootstrap?

**Comment by dominicarrojado** [comment]
Also tried it on a simple meteor create app. And just download this package. persistency still doesn't work..

**Comment by dominicarrojado** [comment]
Oh shit, Now I know why.. the version is the reason, my dropdown package is 1.2.0 and the persistency was added on 1.2.1. :))

**Comment by johanbrook** [comment]
;) It happens the best.
