### ISSUE TITLE
DropDown opens at the far left of page

### ISSUE THREAD

**Issue by kaiyes** [lookback/meteor-dropdowns#11]
Hi, I am using materialize css & using the dropdown inside the nav bar. When I have just the hello world, the dropdown works well (without the bordered box though). But when I start using a reactive list tag in there, it opens far left of the page. The list tag has a link in it, and the link works too. it look like this 
![screen shot 2016-02-14 at 11 25 51 am](https://cloud.githubusercontent.com/assets/5293742/13032041/58052b86-d30e-11e5-8fe0-a3a9ea464a50.png)

![screen shot 2016-02-14 at 12 06 29 pm](https://cloud.githubusercontent.com/assets/5293742/13032194/7a698d5c-d313-11e5-87f0-7c6149791575.png)

the code looks like this. Obviously the list is inside  a nav tag. 
![screen shot 2016-02-14 at 11 33 15 am](https://cloud.githubusercontent.com/assets/5293742/13032050/db00079a-d30e-11e5-8a7f-b920ea309da1.png)

**Comment by johanbrook** [comment]
Hey @kaiyes. It sounds this is an CSS issue? Have you tried setting `position: relative` on the parent element of both the dropdown and trigger?

**Comment by kaiyes** [comment]
Well, Thanks for replying this fast. The counter bubble package was messing with the css. Solving issues on that front solved the problem

**Comment by johanbrook** [comment]
Great!
