### ISSUE TITLE
Dropdown items are not reactively rendered

### ISSUE THREAD

**Issue by bmanturner** [lookback/meteor-dropdowns#2]
Hey, thanks for the great package.

I noticed the dropdown menu does not reactively render helper variables. For example, I would like to generate the menu items using a mongodb cursor.

**Comment by johanbrook** [comment]
Hi @bmanturner! Have you checked out the code in https://github.com/lookback/meteor-dropdowns/blob/master/test-app/demo.coffee ? It uses a local Mongo collection to reactively render drinks in a dropdown menu.

**Comment by bmanturner** [comment]
I had made a silly mistake and jumped the gun on filing an issue. My
apologies.

**Comment by johanbrook** [comment]
No worries!
