### ISSUE TITLE
How to vertically align dropdown elements

### ISSUE THREAD

**Issue by chackerian** [lookback/meteor-dropdowns#4]
I am working on creating several drop-downs within a Navigation Bar. The problem I'm encountering is that the dropdown elements are automatically horizontally aligned from the CSS that styles the other horizontal links in the navbar ( I want them to be vertically aligned like most dropdowns) . I would be curious to know what might be the solution to this issue whether it be using different CSS rules or using the package differently.

![Image](https://raw.githubusercontent.com/chackerian/SpaceTrades/a02bd03196a0c5981c2d66181abc1d570c67e291/public/images/Screen%20Shot%202015-06-28%20at%202.35.28%20AM.png)

My code is as follows:

```
  {{#dropdownTrigger name="uniqueName" }}
<i class="navbarsdown navfa navfai fa fa-globe dropdown__trigger"></i><!-- </button> -->
  {{/dropdownTrigger}}

 {{#dropdown name="uniqueName"}}
<a href="/activities"><span class="pocketwacket">Activities</span></a>
<a href="/meetuprequest"><span class="pocketwacket">Meetup Request Manager</span></a>
<a href="/listingmanager"><span class="pocketwacket">Listing Manager</span></a>
 <a href="/meetuphistory"><span class="pocketwacket">Meetup History</span></a>
<a href="/accountsettings"><span class="pocketwacket">Account Settings</span></a>
{{/dropdown}}
```

**Comment by chackerian** [comment]
Those links (Activities, Meetup Request Manager...etc) load when the globe is clicked

**Comment by chackerian** [comment]
I see that you have done what I'm looking for with the "More" dropdown on lookback.io but remain confused.

**Comment by johanbrook** [comment]
Hi @chackerian, it's probably styles from your navigation that are inherited down into the dropdown. You can fix this by targeting your dropdown(s) more precise in the CSS and align the text correctly.

This is due to the dropdown is rendered *in place* where you have your `{{#dropdown}}` template block. I hope to create a solution later for optionally render dropdowns directly in the `body` tag in order to prevent CSS inheritance.

**Comment by chackerian** [comment]
Yeah, it was styling from inherited rules. I made some changes and works well now. Thanks for the quick response.
