### ISSUE TITLE
How to remove Momentum effect

### ISSUE THREAD

**Issue by MarcTe** [lookback/meteor-dropdowns#5]
Ho do we remove Momentum effect without risk of breaking something in the package?

**Comment by johanbrook** [comment]
@MarcTe I don't think anything will break if you would remove it. Right now, there's no support for having custom Momentum effects or disable effects completely without cloning down this package locally to your app and changing the code yourself. Feel free to file an issue on that.

**Comment by johanbrook** [comment]
Fixed in https://github.com/lookback/meteor-dropdowns/releases/tag/v1.3.0. Also see README.
