### ISSUE TITLE
How do we store/access data local to a dropdown instance?

### ISSUE THREAD

**Issue by MarcTe** [lookback/meteor-dropdowns#6]
As this package is likely a must for meteor and JS beginners (as I am),
keeping in mind the idea that your package keeps local data for each dropdown list:
1) in an example of a dropdown list, especially one from which we want to extract a non displayed value such as where we have an icon+some displayed text+a selection "ID value" (an example of this being a displayed option in French but the logic using the equivalent "ID value" in English as the common value for whatever language version is displayed),
how do we populate the list, store and retrieve the value, without interfering one picklist with the others?

**Comment by johanbrook** [comment]
@MarcTe Each dropdown can use a Meteor template, and thus scope/contain the logic and data. 

```html
{{ > dropdown template="someTemplate" name="myDropdown" }}
```

```js
Template.someTemplate.helpers({
  // ...
});

Template.someTemplate.events({
  // ...
});
```
