### ISSUE TITLE
Can't get dropdown with multiple items to work

### ISSUE THREAD

**Issue by fuzzyshark** [lookback/meteor-dropdowns#7]
I followed the example for Dropdown with multiple items. helpers would show error if not done like this - Template.sometemplate.helpers({
	items:['Foo','Bar','Baz']
});
(Whereas example omits the {}, might mean the same, i'm new at this)
template - 
<template name="sometemplate">
	 {{#dropdownTrigger name=this}}
    <button>Dropdown with {{items.length}} items</button>
  {{/dropdownTrigger}}
  {{#dropdown name=this classes="dropdown--menu" align="left"}}
    <ul class="dropdown__menu">
      {{#each items}}
        <li role="menuItem"><a href="#">{{this}}</a></li>
      {{/each}}
    </ul>
  {{/dropdown}}
</template>

The button shows up but no dropdown options are visible after clicking.

**Comment by johanbrook** [comment]
Hi @fuzzyshark! Did this work out for you?

**Comment by fuzzyshark** [comment]
Sadly no, but someone suggested using auto forms for what i was doing.

**Comment by johanbrook** [comment]
What kind of error was shown?

**Comment by fuzzyshark** [comment]
Didn't get any errors. Just clicking the button didn't show a dropdown.

**Comment by johanbrook** [comment]
Aha, I thought some JS errors were thrown in the console because you stated:

> helpers would show error if not done like this

So there's nothing in the console?

**Comment by fuzzyshark** [comment]
Hi there,

I tried this again, and seems i missed out on configuring the router according to the new template. The dropdown works, but the alignment is a little off. They seem to pop up above the button

**Comment by fuzzyshark** [comment]
Actually just doing this did show an error (Saying unexpected token ":")-

Template.testTemplate.helpers(
  items: ['Foo', 'Bar', 'Baz']
)

But i see other templates use this syntax - 
Template.testTemplate.helpers({
})

So, that worked

**Comment by johanbrook** [comment]
Well, the version with braces left out is CoffeeScript, so it's not valid JS :) 

You can check the docs for alignment and positioning.

**Comment by fuzzyshark** [comment]
That makes sense, thanks :)

**Comment by johanbrook** [comment]
:boom: :)
