### ISSUE TITLE
Dropdowns with meteor server calls break

### ISSUE THREAD

**Issue by kcsavage** [lookback/meteor-dropdowns#8]
We're trying to use the dropdowns to display a list of dynamic choices. After a user selects a choice a `Meteor.call('function',params...` is called. The server side function updates some information in a collection that then in turn is updated in the calling dropdown.

The dropdowns are opened from several buttons on the same page that have the same function. Each item in the collection has dropdown with this function. The dropdowns get a name from the Meteor `Template.created` created method. This allows each dropdown to have a unique name and show for it's given button.

After the call to a server function that updates an item in the collection, the dropdown breaks and becomes unnamed somehow.

Please see [this sample project](https://github.com/kcsavage/testDropdownApp) for a demonstration of the behavior described.

**Comment by johanbrook** [comment]
Hi @kcsavage!

Thanks for a great repro of this!

The pattern I usually take in order to achieve dynamically named dropdowns is to use a **helper** instead.

Like this:

```js
Template.buttonDropdown.helpers({
    dropdownName: function() {
      return this._id;
    }
});
```
```html
<template name="buttonDropdown">
  {{#dropdownTrigger name=dropdownName}}
    <button>Trigger {{this._id}}</button>
  {{/dropdownTrigger}}

  {{#dropdown name=dropdownName}}
    <ul>
      <li class="normal">Normal</li>
      <li class="callback">Call to server {{this.prop}}</li>
    </ul>
  {{/dropdown}}
</template>
```

I tested it in your repro, and it works out fine for me.

**Comment by kcsavage** [comment]
@johanbrook Thanks for your quick reply!

I updated the repro to use the [mquandalle:jade](https://github.com/mquandalle/meteor-jade) package and the templates are now in jade. I was able to do what you suggested just fine. What through me off was having to do this:
```jade
  +dropdownTrigger(name=dropdownName)
    button Trigger #{this._id}
  +dropdown(name=dropdownName)
    ul
      li.normal(class="#{dropdownName}") Normal
      li.callback(class="#{dropdownName}") Call to server #{this.prop}
```

instead of:

```jade
  +dropdownTrigger(name="#{dropdownName}")
    button Trigger #{this._id}
  +dropdown(name="#{dropdownName}")
    ul
      li.normal(class="#{dropdownName}") Normal
      li.callback(class="#{dropdownName}") Call to server #{this.prop}
```

Usually Meteor helpers from jade syntax have to be called using `#{helperName}` syntax. Doing that throws an error from Dropdowns that `#{helperName}` is not found.

Thanks again for your quick response and I hope this can someone else using your dropdowns and jade!

**Comment by johanbrook** [comment]
:boom: Great!
