### ISSUE TITLE
Any way to get subs under dropdown options ?

### ISSUE THREAD

**Issue by fuzzyshark** [lookback/meteor-dropdowns#9]
Something like this : http://jsfiddle.net/49y0kcmb/4/
without using semantic-ui

**Comment by johanbrook** [comment]
I think you could be able to roll that on your own, by hooking up an event listener on hover, and show/hide the sub menu with correct position.

**Comment by fuzzyshark** [comment]
True. I was trying to find if there are some alternatives to slack. Apologies.
